name: CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2

    - name: Restore dependencies
      run: dotnet restore ./Meta.Instagram/Meta.Instagram.sln --configfile

    - name: Build the project
      run: dotnet build ./Meta.Instagram/Meta.Instagram.sln --configuration Release --no-restore

    - name: Deploy to Dev Environment
      run: echo "Deploying to Development environment..."